# Generated by Django 5.2.16 on 2026-07-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parking_id", models.IntegerField()),
                ("parking_code", models.CharField(max_length=50)),
                ("vehicle_number", models.CharField(max_length=20)),
                ("slot_number", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "sos_parking",
            },
        ),
    ]
