# Generated by Django 5.2.16 on 2026-07-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_parking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drone_id", models.IntegerField()),
                ("drone_code", models.CharField(max_length=50)),
                ("operator_name", models.CharField(max_length=20)),
                ("delivery_zone", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "sos_drone",
            },
        ),
    ]
