# Generated by Django 5.2.16 on 2026-07-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_drone"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherAlert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_id", models.IntegerField()),
                ("alert_code", models.CharField(max_length=50)),
                ("city_name", models.CharField(max_length=50)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                ("status", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "weather_alert",
            },
        ),
    ]
