# Generated by Django 5.2.16 on 2026-07-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_weatheralert"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceCommand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command_id", models.IntegerField()),
                ("command_code", models.CharField(max_length=50)),
                ("user_name", models.CharField(max_length=100)),
                ("command_text", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "voice_command",
            },
        ),
    ]
