# Generated by Django 5.2.16 on 2026-07-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('movie_code', models.CharField(max_length=20, unique=True)),
                ('movie_name', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField()),
                ('vehicle_no', models.CharField(max_length=20, unique=True)),
                ('model_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
    ]
