# Generated by Django 5.2.16 on 2026-07-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_movie_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField()),
                ('department_code', models.CharField(max_length=20, unique=True)),
                ('department_name', models.CharField(max_length=100)),
                ('manager_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_id', models.IntegerField(unique=True)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('payment_status', models.CharField(max_length=20)),
            ],
        ),
    ]
