# Generated by Django 5.2.16 on 2026-07-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_department_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_id', models.IntegerField()),
                ('scholarship_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(max_length=15)),
                ('eligibility', models.CharField(max_length=255)),
                ('last_date', models.DateField()),
            ],
            options={
                'db_table': 'scholarship',
            },
        ),
        migrations.AlterModelTable(
            name='fee',
            table='fee',
        ),
    ]
