# Generated by Django 5.2.16 on 2026-08-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_scholarship_alter_fee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('attendance_date', models.DateField()),
                ('student_class', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
