# Generated by Django 5.2.16 on 2026-08-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField(unique=True)),
                ('branch_name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('manager_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'branch',
            },
        ),
    ]
