# Generated by Django 5.2.16 on 2026-08-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField(unique=True)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('card_holder', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('card_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'creditcard',
            },
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='percentage',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='student_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='scholarship_id',
            field=models.IntegerField(unique=True),
        ),
    ]
