# Generated by Django 5.2.16 on 2026-08-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_atm_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('order_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('customer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
