# Generated by Django 5.2.16 on 2026-08-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('holder_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('branch_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bank_account',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=150)),
                ('doctor_name', models.CharField(max_length=100)),
                ('admission_date', models.DateField()),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
