# Generated by Django 5.2.16 on 2026-08-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_bankaccount_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.IntegerField()),
                ('complaint_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('complaint_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
    ]
