# Generated by Django 5.2.16 on 2026-09-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_event_hotel_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(unique=True)),
                ('room_no', models.IntegerField(unique=True)),
                ('room_type', models.CharField(max_length=50)),
                ('price_per_day', models.IntegerField()),
                ('availability', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Room',
            },
        ),
    ]
