# Generated by Django 5.2.16 on 2026-09-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=50, unique=True)),
                ('doctor_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('contact_no', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(unique=True)),
                ('service_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=500)),
                ('service_category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField(unique=True)),
                ('vendor_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Vendor',
            },
        ),
    ]
