# Generated by Django 5.2.16 on 2026-09-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_doctor_service_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libraryId', models.CharField(max_length=50, unique=True)),
                ('libraryName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('totalBooks', models.IntegerField()),
                ('contactNo', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Library',
            },
        ),
    ]
