# Generated by Django 5.2.16 on 2026-09-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(max_length=20, unique=True)),
                ('employeeName', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'employeeRest',
            },
        ),
    ]
