# Generated by Django 5.2.16 on 2026-09-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_employeerest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('contactNo', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'DoctorRest',
            },
        ),
    ]
