# Generated by Django 5.2.16 on 2026-09-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_doctorrest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('serviceCategory', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ServiceRest',
            },
        ),
    ]
